# Generated by Django 4.0.4 on 2022-11-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_created']},
        ),
    ]
